version: "3.1"
services:
  jira:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - jiraVolume:/var/atlassian/application-data/jira 
    environment:
      ATL_JDBC_URL: ""
      ATL_JDBC_USER: "jira_db"
      ATL_JDBC_PASSWORD: "jira_db"
      ATL_DB_DRIVER: "com.mysql.jdbc.Driver"
      ATL_DB_TYPE: "mysql8"
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "jira_db"
      MYSQL_DATABASE: "jira_db"
      MYSQL_USER: "jira_db"
      MYSQL_PASSWORD: "jira_db"
    volumes:
      - /volumes/jira/db/:/var/lib/mysql

volumes:
  jiraVolume:
